'use strict';

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

const sumOfEvenFibonacciNumbers = () => {
  const lastNumbers = [0, 1];
  let accumulator = 0;
  while (lastNumbers[1] <= 4000000){
    const newNumber = lastNumbers[0] + lastNumbers[1];
    lastNumbers[0] = lastNumbers[1];
    lastNumbers[1] = newNumber;
    if (newNumber % 2 === 0){
      accumulator += newNumber;
    }
  }
  return accumulator;
};

console.log(sumOfEvenFibonacciNumbers());